require: rubocop-rspec

inherit_from: .rubocop_todo.yml

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

# shut hound up (stylistic diff w rubocop version?)
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/TrailingBlankLines:
  Enabled: false
