notifications:
  email: ndushay@stanford.edu

rvm:
  - 2.2.2

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
language: ruby


script:
  - bundle exec rake
  - bundle exec rake rubocop
